version: "3.8"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db_phpeso
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD:
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3316:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  php:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      mysql:
        condition: service_started
    environment:
      DB_SERVER: mysql
      DB_NAME: db_phpeso
      DB_USER: root
      DB_PASSWORD: ""

volumes:
  mysql_data:
