version: "3.8"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db_phpeso
      MYSQL_ROOT_PASSWORD:
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3316:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  php:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      mysql:
        condition: service_started

volumes:
  mysql_data:
