version: "3.8"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db_phpeso
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3316:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  php:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      DB_SERVER: mysql
      DB_NAME: db_phpeso
      DB_USER: root
      DB_PASSWORD: ""

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data: